language: node_js
node_js:
#  - "6"
  - "8"
#  - "8.10"
#  - "10"
before_install:
  - 'if [ "$NPM_VERSION" ]; then npm install -g npm@^$NPM_VERSION; fi'
  - 'if [ "$ALT_VERSION" ]; then mkdir tmpnpm && cd tmpnpm && git clone $ALT_VERSION && git checkout -b enoent-on-link-up 52b5011d91e0e98ccdd10ab3063a2837d35dfadd && node . install -g . && cd ..; fi'
  - 'npm --version'
  - 'if [ "$ALT_VERSION" ]; then echo $ALT_VERSION; fi'
before_script:
  - 'npm i -g serverless'
after_success: npm run coverage

env:
#  - NPM_VERSION=6.4.1
#  - NPM_VERSION=5.10.0
#  - NPM_VERSION=5.8.0
#  - NPM_VERSION=5.5.0
  - ALT_VERSION=https://github.com/jtwebman/cli.git
