language: node_js
node_js:
#  - "6"
  - "8"
#  - "8.10"
#  - "10"
before_install:
  - 'if [ "$NPM_VERSION" ]; then npm install -g npm@^$NPM_VERSION; fi'
  - 'if [ "$ALT_VERSION" ]; then npm install -g $ALT_VERSION; fi'
  - 'npm --version'
  - 'if [ "$ALT_VERSION" ]; then echo $ALT_VERSION; fi'
before_script:
  - 'npm i -g serverless'
after_success: npm run coverage

env:
  - NPM_VERSION=6.4.1
  - ALT_VERSION=github:jtwebman/cli#enoent-on-link-up
